package com.softserve.edu.library2.dao.entities;

// Generated Aug 20, 2015 4:19:05 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BookCopyReader generated by hbm2java
 */
@Entity
@Table(name = "book_copy_reader", catalog = "library")
public class BookCopyReader implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3473416867836800803L;
	private BookCopyReaderId id;
	private Book book;
	private BookCopy bookCopy;
	private Reader reader;

	public BookCopyReader() {
	}

	public BookCopyReader(BookCopyReaderId id, Book book, BookCopy bookCopy, Reader reader) {
		this.id = id;
		this.book = book;
		this.bookCopy = bookCopy;
		this.reader = reader;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "readerId", column = @Column(name = "reader_id", nullable = false)),
			@AttributeOverride(name = "isbn", column = @Column(name = "isbn", nullable = false)) })
	public BookCopyReaderId getId() {
		return this.id;
	}

	public void setId(BookCopyReaderId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "isbn", nullable = false, insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_copy_id", nullable = false)
	public BookCopy getBookCopy() {
		return this.bookCopy;
	}

	public void setBookCopy(BookCopy bookCopy) {
		this.bookCopy = bookCopy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reader_id", nullable = false, insertable = false, updatable = false)
	public Reader getReader() {
		return this.reader;
	}

	public void setReader(Reader reader) {
		this.reader = reader;
	}

}
